install.packages("dplyr", repos = "http://cran.us.r-project.org")
install.packages("textstem", repos = "http://cran.us.r-project.org")
install.packages("tidytext", repos = "http://cran.us.r-project.org")
install.packages("text2vec", repos = "http://cran.us.r-project.org")
install.packages("devtools", repos = "http://cran.us.r-project.org")
remotes::install_github("https://github.com/stephbuon/dhmeasures", dependencies = TRUE, upgrade = TRUE, force = TRUE)